import { curriculumCatalog } from '@lailai/academy-shared';
import type { CourseDefinition } from './types.js';

const catalog = curriculumCatalog.courses.find((course) => course.slug === 'physics-momentum');

if (!catalog) {
  throw new Error('Momentum course is missing from the curriculum catalog.');
}

export const momentumCourse: CourseDefinition = {
  catalog,
  version: '2026.09.1',
  lessonSteps: [
    {
      id: 'orientation',
      kind: 'reading',
      phase: 'foundation',
      title: '先确定研究对象、过程和正方向',
      instruction: '这三个选择会决定后续每一个符号和方程。',
      questionsAvailable: true,
      content: [
        {
          kind: 'paragraph',
          text: '动量题不要从套公式开始。先写清研究对象，圈出研究过程的起止时刻，再选择一个正方向。',
        },
        {
          kind: 'bullets',
          items: [
            '研究对象决定哪些力属于外力。',
            '起止时刻决定动量变化对应哪一段过程。',
            '正方向决定速度、冲量和动量变化的符号。',
          ],
        },
        {
          kind: 'callout',
          title: '本课约定',
          text: '竖直反弹问题统一取向上为正。向下的速度必须写成负值。',
        },
      ],
    },
    {
      id: 'foundation-direction',
      kind: 'question',
      phase: 'foundation',
      title: '检查带符号的速度',
      instruction: '先独立选择。答错后可以查看提示再试。',
      question: '小球以 6 m/s 竖直向下运动，取向上为正。碰地前速度应写成什么？',
      responseKind: 'choice',
      options: ['+6 m/s', '-6 m/s', '0', '无法确定'],
      answer: { kind: 'exact', accepted: ['-6 m/s', '-6m/s'] },
      correctFeedback: '方向与正方向相反，因此速度是 -6 m/s。',
      incorrectFeedback: '速率是 6 m/s，但速度还需要带上相对正方向的符号。',
      hint: '先画一条竖直数轴，把“向上”标成正方向。',
      solution: '向下与正方向相反，所以 v₁ = -6 m/s。',
      questionsAvailable: true,
    },
    {
      id: 'foundation-system',
      kind: 'question',
      phase: 'foundation',
      title: '检查系统与外力',
      instruction: '判断时只研究“球”本身。',
      question: '球与地面碰撞并反弹的短暂过程中，能否说“球的动量守恒”？',
      responseKind: 'choice',
      options: [
        '能，因为碰撞时间很短',
        '能，因为重力可以忽略',
        '不能，因为地面对球有明显外力冲量',
        '不能，因为球的质量发生变化',
      ],
      answer: { kind: 'exact', accepted: ['不能，因为地面对球有明显外力冲量'] },
      correctFeedback: '研究对象只有球，地面对球的作用属于外力，且冲量不可忽略。',
      incorrectFeedback: '碰撞时间短并不自动意味着外力冲量为零。先确认研究对象。',
      hint: '如果研究对象只有球，地面对球的力是内力还是外力？',
      solution: '地面对球的作用是外力，冲量明显，因此球自身的动量不守恒。',
      questionsAvailable: true,
    },
    {
      id: 'impulse-momentum',
      kind: 'reading',
      phase: 'lesson',
      title: '动量定理描述的是合外力冲量',
      instruction: '把公式中的每一项都对应到同一个研究对象和同一段过程。',
      questionsAvailable: true,
      content: [
        {
          kind: 'formula',
          expression: 'I合 = Δp = m(v₂ - v₁)',
        },
        {
          kind: 'paragraph',
          text: '恒力时，合外力冲量可以写成 F合·Δt；变力时，力—时间图像的有向面积表示冲量。',
        },
        {
          kind: 'callout',
          title: '容易混淆的地方',
          text: 'F合 是合外力，不一定等于题目所求的支持力、拉力或阻力。求具体作用力时还要完成受力分析。',
        },
      ],
    },
    {
      id: 'practice-momentum-change',
      kind: 'question',
      phase: 'practice',
      title: '先计算动量变化',
      instruction: '质量 0.5 kg 的球以 6 m/s 向下撞地，随后以 4 m/s 向上反弹。取向上为正。',
      question: '球的动量变化量 Δp 是多少 kg·m/s？只填写数值。',
      responseKind: 'number',
      inputLabel: 'Δp',
      answer: { kind: 'number', value: 5, tolerance: 0.01 },
      correctFeedback: 'Δp = 0.5 × [4 - (-6)] = 5 kg·m/s，方向向上。',
      incorrectFeedback: '请检查碰前速度的负号，并使用“末动量减初动量”。',
      hint: '先写 v₁ = -6 m/s，v₂ = 4 m/s，再代入 m(v₂-v₁)。',
      solution: 'Δp = 0.5 × [4 - (-6)] = 5 kg·m/s。',
      questionsAvailable: true,
    },
    {
      id: 'practice-contact-force',
      kind: 'question',
      phase: 'practice',
      title: '从合力回到支持力',
      instruction: '沿用上一题，接触时间为 0.02 s，取 g = 10 m/s²。',
      question: '地面对球的平均作用力是多少 N？方向向上，只填写大小。',
      responseKind: 'number',
      inputLabel: '平均作用力',
      answer: { kind: 'number', value: 255, tolerance: 0.1 },
      correctFeedback: '合外力平均值为 250 N；再由 N - mg = 250 N，得到 N = 255 N。',
      incorrectFeedback: '由 Δp/Δt 得到的是合外力。球还受到重力，需要再列 N - mg = F合。',
      hint: '先算合外力 5/0.02，再画球的受力图。',
      solution: 'F合 = 250 N，mg = 5 N，所以 N = F合 + mg = 255 N。',
      questionsAvailable: true,
    },
    {
      id: 'assessment-bounce',
      kind: 'question',
      phase: 'assessment',
      title: '独立测评：更换数据',
      instruction: '本题不提供提示。提交后无论对错都会进入下一题。',
      question:
        '质量 0.25 kg 的球以 8 m/s 向下撞地，随后以 4 m/s 向上反弹，接触时间 0.05 s。取 g = 10 m/s²。地面对球的平均作用力大小是多少 N？',
      responseKind: 'number',
      inputLabel: '平均作用力',
      answer: { kind: 'number', value: 62.5, tolerance: 0.1 },
      correctFeedback: 'Δp = 3 kg·m/s，合外力为 60 N，支持力为 62.5 N。',
      incorrectFeedback: '正确结果是 62.5 N。复盘时检查速度符号，以及合外力与支持力的区别。',
      advanceOnIncorrect: true,
      questionsAvailable: false,
    },
    {
      id: 'assessment-wall',
      kind: 'question',
      phase: 'assessment',
      title: '独立测评：水平反弹',
      instruction: '换了方向和受力情境，需要重新选择正方向。',
      question:
        '质量 0.4 kg 的球以 5 m/s 垂直撞向墙壁，随后以 2 m/s 反向弹回，接触时间 0.02 s。墙对球的平均作用力大小是多少 N？',
      responseKind: 'number',
      inputLabel: '平均作用力大小',
      answer: { kind: 'number', value: 140, tolerance: 0.1 },
      correctFeedback: '冲量大小为 0.4 × (5 + 2) = 2.8 N·s，平均力大小为 140 N。',
      incorrectFeedback: '正确结果是 140 N。反弹后速度与碰前方向相反，动量变化不是 0.4×(5-2)。',
      advanceOnIncorrect: true,
      questionsAvailable: false,
    },
  ],
  retestSteps: [
    {
      id: 'retest-bounce',
      kind: 'question',
      phase: 'retest',
      title: '延迟复测：竖直反弹',
      instruction: '不查看原课程，独立完成。',
      question:
        '质量 0.2 kg 的球以 8 m/s 向下撞地，随后以 3 m/s 向上反弹，接触时间 0.04 s。取 g = 10 m/s²。支持力大小是多少 N？',
      responseKind: 'number',
      inputLabel: '支持力大小',
      answer: { kind: 'number', value: 57, tolerance: 0.1 },
      correctFeedback: '动量变化为 2.2 kg·m/s，合外力为 55 N，支持力为 57 N。',
      incorrectFeedback: '正确结果是 57 N。请回看速度符号和支持力换算。',
      advanceOnIncorrect: true,
      questionsAvailable: false,
    },
    {
      id: 'retest-wall',
      kind: 'question',
      phase: 'retest',
      title: '延迟复测：水平碰墙',
      instruction: '只填写力的大小。',
      question:
        '质量 0.5 kg 的球以 6 m/s 撞向墙壁，随后以 2 m/s 反向弹回，接触时间 0.04 s。墙的平均作用力大小是多少 N？',
      responseKind: 'number',
      inputLabel: '平均作用力大小',
      answer: { kind: 'number', value: 100, tolerance: 0.1 },
      correctFeedback: '动量变化量的大小为 4 N·s，平均作用力大小为 100 N。',
      incorrectFeedback: '正确结果是 100 N。反弹前后速度方向相反。',
      advanceOnIncorrect: true,
      questionsAvailable: false,
    },
    {
      id: 'retest-impulse',
      kind: 'question',
      phase: 'retest',
      title: '延迟复测：由冲量求末速度',
      instruction: '注意冲量和动量都有方向。',
      question:
        '质量 1 kg 的物体初速度为 -1 m/s，随后受到正方向 4 N·s 的合外力冲量。末速度是多少 m/s？',
      responseKind: 'number',
      inputLabel: '末速度',
      answer: { kind: 'number', value: 3, tolerance: 0.01 },
      correctFeedback: '初动量为 -1 kg·m/s，末动量为 3 kg·m/s，所以末速度为 3 m/s。',
      incorrectFeedback: '正确结果是 3 m/s。使用 p₂ = p₁ + I。',
      advanceOnIncorrect: true,
      questionsAvailable: false,
    },
  ],
};
