export const pagePaths = [
  ['/', 'LandingPage'],
  ['/login', 'AuthPage'],
  ['/register', 'AuthPage'],
  ['/onboarding', 'OnboardingPage'],
  ['/dashboard', 'DashboardPage'],
  ['/courses', 'CoursesPage'],
  ['/courses/:courseSlug/run/:runId', 'CoursePlayerPage'],
  ['/learn', 'LearnPage'],
  ['/learn/words', 'LearnPage'],
  ['/learn/poems', 'LearnPage'],
  ['/learn/mistakes', 'MistakesPage'],
  ['/learn/session/:sessionId', 'SessionPage'],
  ['/progress', 'ProgressPage'],
  ['/social', 'SocialPage'],
  ['/profile', 'ProfilePage'],
  ['/profile/:username', 'ProfilePage'],
  ['/settings', 'SettingsPage'],
  ['/admin/*', 'AdminPage'],
] as const;
