import {
  ArrowLeft,
  ArrowRight,
  Atom,
  BadgeCheck,
  Bell,
  BookOpen,
  Brain,
  CalendarDays,
  ChartNoAxesColumn,
  ChartNoAxesCombined,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleStop,
  CircleX,
  Feather,
  FlaskConical,
  Globe2,
  Heart,
  History,
  House,
  Info,
  Languages,
  Lightbulb,
  ListChecks,
  Lock,
  LogOut,
  Menu,
  NotebookTabs,
  Pause,
  Play,
  RotateCcw,
  Save,
  ScanSearch,
  Search,
  Settings2,
  ShieldCheck,
  Sigma,
  Sparkles,
  Target,
  UserRound,
  Users,
  Upload,
  X,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

const icons: Record<string, LucideIcon> = {
  'lucide:arrow-left': ArrowLeft,
  'lucide:arrow-right': ArrowRight,
  'lucide:atom': Atom,
  'lucide:badge-check': BadgeCheck,
  'lucide:bell': Bell,
  'lucide:book-open': BookOpen,
  'lucide:brain': Brain,
  'lucide:calendar-days': CalendarDays,
  'lucide:chart-no-axes-column': ChartNoAxesColumn,
  'lucide:chart-no-axes-combined': ChartNoAxesCombined,
  'lucide:check-circle-2': CheckCircle2,
  'lucide:chevron-down': ChevronDown,
  'lucide:chevron-right': ChevronRight,
  'lucide:circle-stop': CircleStop,
  'lucide:circle-x': CircleX,
  'lucide:feather': Feather,
  'lucide:flask-conical': FlaskConical,
  'lucide:globe-2': Globe2,
  'lucide:heart': Heart,
  'lucide:history': History,
  'lucide:house': House,
  'lucide:info': Info,
  'lucide:languages': Languages,
  'lucide:lightbulb': Lightbulb,
  'lucide:list-checks': ListChecks,
  'lucide:lock': Lock,
  'lucide:log-out': LogOut,
  'lucide:menu': Menu,
  'lucide:notebook-tabs': NotebookTabs,
  'lucide:pause': Pause,
  'lucide:play': Play,
  'lucide:rotate-ccw': RotateCcw,
  'lucide:save': Save,
  'lucide:scan-search': ScanSearch,
  'lucide:search': Search,
  'lucide:settings-2': Settings2,
  'lucide:shield-check': ShieldCheck,
  'lucide:sigma': Sigma,
  'lucide:sparkles': Sparkles,
  'lucide:target': Target,
  'lucide:user-round': UserRound,
  'lucide:users': Users,
  'lucide:upload': Upload,
  'lucide:x': X,
};

type IconProps = Omit<LucideProps, 'ref'> & { icon: string };

export function Icon({ icon, ...props }: IconProps) {
  const Component = icons[icon];
  return Component ? <Component aria-hidden="true" {...props} /> : null;
}
